### ISSUE TITLE
Hypar geometry converters

### ISSUE THREAD

**Issue by radumg** [hypar-io/elements#112]
@markthorley has a bare-bones implementation that translates `Hypar` geometry to `Dynamo` geometry, so we had a couple of questions :

- is this something you'd like maintained as part of Hypar org @ikeough or as community packages ? we'd be happy to contribute it.
- looking at the repo/org, where would such a converter go ? It's unclear to me at the moment what the `Revit` & `Unity` folders are for example, though i assume they're either converters or some kind of samples of how to use `Elements` on those platforms (in which case they might be better destined for an `Elements-samples` repo?)

If we do like the idea of having converters here somewhere, happy to discuss how to structure them, have a few ideas 😎

**Comment by ikeough** [comment]
My first instinct is to put these in a separate project. Something like `Elements.Dynamo`, which would get its own nuget. I would like to do the same with `Elements.Revit` if we continue support for Revit translation. `Elements.Dynamo` would have two things, a nice Dynamo-like API. Ex: `Wall.ByCenterlineOpenings(...)` and the necessary geometry converters.

Your confusion about the `Revit` and `Unity` folders is understood. They were meant as a examples, and should probably be moved somewhere with a name fitting that purpose.

**Comment by radumg** [comment]
Sounds good - would you like to set up a repo in `hypar-io` org so that we can fork & start migrating our code to it ? If not, we can set up a repo and transfer ownership if/when happy with it.

**Comment by ikeough** [comment]
I think we can leave it in elements for now. I'll add a folder it for it.

**Comment by ikeough** [comment]
There's now a folder,`src/Dynamo, with a stub project in it. Please make a PR to add the conversion stuff there.

**Comment by ikeough** [comment]
I'm closing this. The folder is there if you want to use it @radumg.
