### ISSUE TITLE
Geometry not rendering correctly in glTF

### ISSUE THREAD

**Issue by MarkThorley** [hypar-io/elements#118]
It seems that solids arent rendering correctly when exported to glTF. As you can see from the two images the vertices of the solid hypar element are not consistent with the glTF edge lines. 

![image](https://user-images.githubusercontent.com/6421438/54129121-7b8eeb80-4405-11e9-9604-5b6dfa2042d8.png)

![image](https://user-images.githubusercontent.com/6421438/54129161-8ea1bb80-4405-11e9-98d6-824ed2f84d11.png)

**Comment by ikeough** [comment]
Can you give me a reproduceable example? I'm not sure what I'm supposed to be seeing in the provided image.

**Comment by MarkThorley** [comment]
So in the first Dynamo node you are seeing the vertices of the solid, where there is a series of points at Z=0 and Z=3200. This makes up the first solid shape at the bottom of the geometry glTF viewer. The second Dynamo node shows the vertices of the next solid Z=3200 and Z=6400. This means that the two geometries should be sat on top of one another, yet in the viewer there is a gap between each solid.

**Comment by MarkThorley** [comment]
Apologies, I think I found the issue as I was using a transform when creating the mass and replicating the height parameter.

**Comment by ikeough** [comment]
Hooray for user error! Just kidding :). If anything seems like it could be better in those APIs let us know.
