### ISSUE TITLE
JSON model read doesn't like numbers

### ISSUE THREAD

**Issue by natgmac** [hypar-io/Elements#129]
using Elements.Model.FromJSON will throw an error if any property unit type is "none" and its value is a number. See lines below.

https://github.com/hypar-io/elements/blob/b61f03df51c6bffc875e49644982f572c84e7080/src/Elements/Serialization/PropertyDictionaryConverter.cs#L30-L42

A quick fix would be to rename "volume" to "number". Or allow the "none" type to have any data type.

**Comment by ikeough** [comment]
I believe this is now resolved with all the work we've done around property support, code generation, etc.
