### ISSUE TITLE
Elements 2.3 doesn't respect material color assignments

### ISSUE THREAD

**Issue by hummingburd** [hypar-io/elements#134]
Referencing Elements 2.3, this line of code adds a white cube to the model instead of a red one:             model.AddElement(new Space(Polygon.Rectangle(100.0, 100.0, Vector3.Origin), 100.0, 0.0, new Material("", new Elements.Geometry.Color(1.0f, 0.0f, 0.0f, 1.0f))));

**Comment by hummingburd** [comment]
![image](https://user-images.githubusercontent.com/33582525/56652827-969f7d00-668c-11e9-9981-25ede097e65c.png)

**Comment by hummingburd** [comment]
Elements 2.2:
![image](https://user-images.githubusercontent.com/33582525/56652963-e5e5ad80-668c-11e9-871c-791bbb50c358.png)

**Comment by ikeough** [comment]
@hummingburd  is this a duplicate of #138? If so, can we close?

**Comment by hummingburd** [comment]
Yes. Closing.
