### ISSUE TITLE
GitHub releases & release notes are not in sync with NuGet package

### ISSUE THREAD

**Issue by radumg** [hypar-io/elements#140]
Was re-installing some of our internal NuGet packages when I noticed that `Hypar.Elements` has a `0.2.4.3` release available.

![image](https://user-images.githubusercontent.com/11439624/57845257-87ae7500-77c9-11e9-934a-a7f8f882774d.png)

This came as a bit of a surprise as I wasn't aware of it, despite watching releases on Github. [Release docs](https://github.com/hypar-io/elements/blob/master/CHANGELOG.md) also don't mention it at all, so as a dev consuming this it's hard to anticipate impact surface area.

![image](https://user-images.githubusercontent.com/11439624/57845340-b88eaa00-77c9-11e9-98d6-97c531455f0f.png)

We'd help, but not sure we can given publishing releases should most likely sit in the CI/CD pipeline ? Let us know @ikeough 😄

**Comment by ikeough** [comment]
You are correct @radumg. We're trying to get better about this. Should be up to date now.
