### ISSUE TITLE
Openings in Floors are not exported to IFC

### ISSUE THREAD

**Issue by simonmoreau** [hypar-io/Elements#144]
Below are the Floor created in FloorTests with two openings :

* The GLB floor (seen in the VS Code extension :
![Floor glb](https://user-images.githubusercontent.com/5792167/58238425-893ae880-7d47-11e9-8633-456d4f42dcfe.png)

* The IFC floor (seen in BIM Vision) :
![Floor ifc](https://user-images.githubusercontent.com/5792167/58238335-5bee3a80-7d47-11e9-90d2-2645b1db455b.png)

The openings are not properly added in IFC

**Comment by ikeough** [comment]
![image](https://user-images.githubusercontent.com/1139788/58739615-14f3eb00-83c0-11e9-9735-d31aaba48a2d.png)
