### ISSUE TITLE
0.2.15 doesn't include latest pull requests

### ISSUE THREAD

**Issue by wynged** [hypar-io/Elements#156]
@ikeough 
Somehow this 0.2.15 doesn't seem to include either of the two most recent pull requests.  My Iaggregate elements are still not showing up in the mode, and the save gltf function still leaves the .bin file in a spot not directly adjacent to the bin.
#154 was definitely supposed to be in the nuget version.
Thanks for more help.

**Comment by ikeough** [comment]
Grrr. This is most likely due to some new build tooling that we’ve instituted not pulling the latest. I’ll take a look.

**Comment by ikeough** [comment]
Although it looks like those changes made it into the build, I've published a new version, 0.2.16. Please see if that resolves the issue.

**Comment by wynged** [comment]
you've done it!  my function has been published successfully!
