### ISSUE TITLE
Function generation results in out of memory exceptions.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#158]
From email:

> for (int i = 0; i < Math.min(units.Count, 1600); ++i)
>  model.AddElement(new Mass(units[i], 10);
> 
> where units is an array of ~3k Polygons.  Removing the hard limit
> bricks the computer.  At one point I was able to kill the process
> before the machine stopped responding and it reported an out of memory
> exception in GltfExtensions::AddLines.  No idea if that's an accurate
> report given the circumstances though.

> Errors (most to least common):
> 
> Hypar shows "One or more errors occurred. (Unexpected character
> encountered while parsing value: P. Path '', line 0, position 0.)",
> and the div has a title of "at
> System.Threading.Tasks.Task`1.GetResultCore(Boolean
> waitCompletionNotification),at lambda_method(Closure , Stream , Stream
> , LambdaContextInternal )".  I have no ideas on this one, haven't look
> into it at all.
> 
> "One or more errors occurred. (Building generation failed)."  This is
> reported by my code, I'm just including it to make sure you ignore it.
> I have a feeling most of these are due to sites being too small for
> the given dimension input, but as I mentioned before it's hard to
> track down.
> 
> The tile just says 'No preview available'. Happens pretty infrequently.

**Comment by ikeough** [comment]
The reference to `GlTFExtensions.AddLine()` suggests that performance and memory consumption when adding the edges to the gltf is poor.

**Comment by ikeough** [comment]
The error was due to a loop that never exited. When the size of the edges array is larger than the size of a `ushort`(type used for indices in glTF) and you use a `ushort` as the index on a for loop, the index will reset to 0 when the value becomes greater than 65034. This caused the loop to never terminate.

The attached screenshot shows the other issue that will need to be solved when the loop is fixed, which is that now the index resets. We will need to chunk edge writing into buffers no longer than 65034.

```csharp
for (var i = 0; i < vertices.Length; i += 2)
            {
                indices[i] = (ushort)i;
                indices[i+1] = (ushort)(i+1);
                idx++;
            }
```

![image](https://user-images.githubusercontent.com/1139788/60305632-208def80-9935-11e9-8969-bdd7cab75015.png)

**Comment by ikeough** [comment]
And here's a version with 100x100. 
```
Saved Performance_Edges to glb: models/Performance_Edges.glb.(00:00:06.3101260)
```
![image](https://user-images.githubusercontent.com/1139788/60375916-394be300-99d1-11e9-83e7-9122c6e3e6b2.png)

**Comment by hummingburd** [comment]
In case it matters, I ran into this situation without site selection. Buried in this function is some JSON defining a site boundary:

![image](https://user-images.githubusercontent.com/33582525/60535573-6f8baa00-9cd2-11e9-89b6-9a27b104d7c6.png)

**Comment by ikeough** [comment]
Can you tell me which function is running above?

**Comment by ikeough** [comment]
Opened #162 to track the JSON parsing error.

**Comment by hummingburd** [comment]
That's "Mass". 
Which reminds me that I've been meaning to file an enhancement to tell you what function you're using.
