### ISSUE TITLE
Deserialization of Elements.Spaces from JSON fails to set Space.Name property

### ISSUE THREAD

**Issue by anthonyhauck** [hypar-io/Elements#168]
**Describe the bug**
Creating a model with...
var model = Model.FromJson(System.IO.File.ReadAllText("../../../../story.json")); 
... leaves the Space.Name property set to null even though the JSON lists a value for Space.Name.

**To Reproduce**
Read the attached JSON file (submitted as txt to please GitHub) 
[story.txt](https://github.com/hypar-io/Elements/files/3364953/story.txt)
using Model.FromJson and check the Space.Name property using:
var spaces = model.ElementsOfType<Space>().ToList();

**Expected behavior**
Space.Name to be deserialized to each associated space summarized in the JSON.

**Screenshots**
![image](https://user-images.githubusercontent.com/33582525/60760172-07ed9b80-9fff-11e9-8e94-cfafa28c905d.png)
![image](https://user-images.githubusercontent.com/33582525/60760200-5438db80-9fff-11e9-9a76-bb7b48e70f8b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Google Chrome is up to date
Version 75.0.3770.100 (Official Build) (64-bit)

**Additional context**

**Comment by alvpickmans** [comment]
Without knowing if you guys have a post/pre process step when serialize/deserialize, from the images above it seems that the `Name` is being added to the `Properties` dictionary instead of to the `Name` property, so on deserialize it returns `null`.

It is strange though that the `Properties` dictionary does not get populated with values from the JSON file (count returns 0 when it should have two entries for `name` and `area`)

**Comment by ikeough** [comment]
@hummingburd I believe @alvpickmans has recognized a possible error in your logic. The `Name` property (a property on the base class `Element`) is not being set, so should not be expected to be deserialized. Is this understanding correct?

**Comment by hummingburd** [comment]
Could be! Let me check. Code has been revised since but I'll cycle through a Name set and see if I was mistaken.

**Comment by ikeough** [comment]
I believe this issue is obsolete as we’ve moved to a different code generation and serialization stack. If the problem persists, I’m happy to reopen the issue.
