### ISSUE TITLE
Easy way to access added properties

### ISSUE THREAD

**Issue by anthonyhauck** [hypar-io/Elements#171]
**Is your feature request related to a problem? Please describe.**
After using AddProperty I was confounded by the required syntax in trying to access the recorded value downstream. 

**Describe the solution you'd like**
Perhaps something like "Element.GetPropertyByName" and "Elements.GetPropertiesByType" would work. Willing to discuss the design further because I haven't thought this through entirely.

**Describe alternatives you've considered**
I assume there are a few more steps I could go through to access the value(s) I've recorded with AddProperty. A code snippet on the best way to do that would be a stopgap to the full request.

**Comment by ikeough** [comment]
The concept of added properties no longer exists on elements. Element properties are now defined in the schemas and converted to C# code where they can be accessed via dot notation ex: `Foo.Bar`.
