### ISSUE TITLE
Improve glTF render speed by skipping intermediate Mesh creation.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#177]
**Is your feature request related to a problem? Please describe.**
Generating glTF buffers from solids is slower than it needs to be, possibly by an order of magnitude. When generating buffers for glTF we currently tessellate a solid, then create vertices and faces for a mesh, only to then turn right around and pull the buffers from that mesh. 

**Describe the solution you'd like**
The mesh creation step could be skipped completely, and the tessellated face data could be written directly to the buffers.

**Comment by ikeough** [comment]
@radumg This may be the source of your 60ms write to glTF concern :)

**Comment by ikeough** [comment]
By writing directly to buffers we save 40ms. This is not as much as I had anticipated, but is worthwhile.

Before:
```
glTF: 00:00:00.1611180 elapsed for getting render data for nodes.
```
After:
```
glTF: 00:00:00.1205220 elapsed for getting render data for nodes.
```

**Comment by radumg** [comment]
🙌 this is awesome, thanks Ian !
