### ISSUE TITLE
Profiles should have Intersect methods similar to polygons.

### ISSUE THREAD

**Issue by wynged** [hypar-io/Elements#185]
**Describe the solution you'd like**
I want to be able to do `profile.Intersects(profile)` and `profile.Intersect(profile)` to generate new geometry

**Describe alternatives you've considered**
I tried to get buy with polygons, but it just doesn't work.

I have some code started already, it's similar to the Union pull request done previously

**Comment by ikeough** [comment]
Can you explain the use case a little more? `Profile.Intersects()` will return whether the profiles interesect, will it not? How does that help in generating geometry?

**Comment by wynged** [comment]
It doesn't generate geometry directly rather, I have a use for it while
determining if two profiles should be unioned.  If they don't intersect, I
need to not union them (or intersect or difference) and use them
separately.  The intersects method that takes in another profile should
return a new shape where the profiles overlap, with mutual hole regions
also appearing as holes in the new profile

**Comment by ikeough** [comment]
`Profile.Intersection` has now existed for a while.
