### ISSUE TITLE
Elements.Geometry.Polygon.Circle() should return special case true circle

### ISSUE THREAD

**Issue by secretlyagoblin** [hypar-io/Elements#190]
**Is your feature request related to a problem? Please describe.**
While I completely understand and agree with the restriction of a profile as being defined only by a polyline, pipes are a very common profile and the current process of generating a facetted shape results in poor visual quality when exported to IFC.

**Describe the solution you'd like**
In my mind, you could resolve this case by still treating the result as a polyline but keeping the properties we need downstream for calculating area, or passing the circle on to IFC:

```
public class Circle: Polygon{

         public static double Radius;
         public static Plane Plane; //assuming origin and orientation isn't held anywhere else
         
         public Circle(double radius = 1, int divisions = 10){
                 ........
        }
}
```

We can then type check in the IFC exporter and resolve the circle as a special case. 

**Describe alternatives you've considered**
An alternative is to expand in general what can be a profile to include curves (effectively polyline becomes polycurve) but I generally agree with your current design of using polylines only.

There could also be a special case 'piping' element that takes a rail, a radius, and a thickness, but that's replicating a lot of what we'd want in a profile anyway.

**Comment by ikeough** [comment]
There are now `Circle` and `Arc` classes. `Polygon.Circle` will be deprecated.
