### ISSUE TITLE
Elements library documentation is not available

### ISSUE THREAD

**Issue by natgmac** [hypar-io/Elements#194]
The documentation for the elements library is not available anymore. 

![image](https://user-images.githubusercontent.com/29259470/68072355-33895400-fd5b-11e9-896b-56e9dc447794.png)
![image](https://user-images.githubusercontent.com/29259470/68072358-3edc7f80-fd5b-11e9-8945-a615adc6a7c1.png)

Go to hypar.io
Click on "our open source elements library"

Attempted with firefox and chrome and both 404'd.

**Comment by ikeough** [comment]
Wow. Thanks Nat. Looking into it.

**Comment by ikeough** [comment]
This should be fixed now @natgmac. Thanks for the warning.
