### ISSUE TITLE
Space Constructor seems to ignore Elevation argument

### ISSUE THREAD

**Issue by anthonyhauck** [hypar-io/Elements#198]
I think it's the same bug as the id issue:

![image](https://user-images.githubusercontent.com/33582525/68223573-05a24a80-ffbb-11e9-99c8-b262f427fede.png)

**Comment by ikeough** [comment]
I vote to remove the elevation parameter from space altogether as we move towards relative coordinate systems. In the near term this would require that you set the transform explicitly. In the long term the space would be the child of an element like a "level" whose transform would set its elevation.

**Comment by anthonyhauck** [comment]
I agree. Let's trash Elevation. Before I read your comment I just made an explicit Transform and it worked fine. Let's make it consistent.

**Comment by ikeough** [comment]
Fixed in 43f2db5d281da0957a63ee4ed6a33c06cda671b2.
