### ISSUE TITLE
Cannot export result of default function in 0.4.0-alpha.11

### ISSUE THREAD

**Issue by mattc** [hypar-io/Elements#216]
**Describe the bug**
Exporting now requires globally-accessible schema files. However, it seems like the Elements library implicitly adds dependencies on several relatively-pathed schemas (at least in the default template that creates an Envelope): Envelope, Level, and FacadePanel. This breaks even the default `hypar new` function, which has no explicit element_types.

**To Reproduce**
1. Create a new function using `hypar new` and let it publish to Hypar
2. Create a workflow and add that function.
3. Click any of the export buttons (IFC, GLTF, JSON)
4. See error.

**Expected behavior**
All element_types dependencies should be absolute paths to publicly-accessible schemas, so that no error will be thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/48925/70268556-b6446b00-176e-11ea-915a-2165add85309.png)

**Comment by ikeough** [comment]
In explore, we gather the schemas declared by the function and send them to the request to do the model merge. My guess would be that the uris of those schemas are being sent as part of the request, which means that Explore thinks that function requires those schemas.

**Comment by ikeough** [comment]
Fixed in https://github.com/hypar-io/Explore/pull/292/commits/38a8fb313b596cb2850e081c8390c3e2ee529f7b.
