### ISSUE TITLE
Support for non-planar sweeps

### ISSUE THREAD

**Issue by secretlyagoblin** [hypar-io/Elements#220]
I need to generative existing in-ground services that are derived from 3d polylines. Currently, I'm doing this by breaking up the polylines into individual straight sections.

Ideally I would like to be able to specify a 3d curve, a profile, and an 'up' vector and have that generate any sweep.

**Comment by secretlyagoblin** [comment]
I built the repo and disabled the validator checks, and the 3d pipes work well enough in gltf for now - that'll tide me over until the new year!

![image](https://user-images.githubusercontent.com/13952064/70954499-52a53080-20d2-11ea-9ac1-84c5a07e6110.png)

**Comment by secretlyagoblin** [comment]
Works as of latest version

**Comment by ikeough** [comment]
Cool to see that you have a version of this that works. It might be that we can provide a flag when you construct the polyline to enforce planarity. Like `new Polyline(List<Vector3> vertices, bool enforcePlanar = true)`. What kind of 3D curves would be most useful?

**Comment by secretlyagoblin** [comment]
Hey Ian, I think your suggestion makes sense - you might also make the exception it throws more descriptive as a result to indicate that sweeping in 3d can have unintuitive results.

Having spent a bit more time prototyping, I've realised our use case is more complicated and specific than I first thought - so I'll leave this closed for now and open another suggestion that better encompasses what we want to do.
