### ISSUE TITLE
Beams not exported to IFC (0.4.3.4)

### ISSUE THREAD

**Issue by angellinares** [hypar-io/Elements#229]
**Describe the bug**
Beams elements created with a function built using 0.4.3.4 version are not exported to IFC

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new custom function.
2. Create a beam with the required construction inputs.
3. Add this beam to the output: _output.model.AddElement(cBeam);_
4. Hypar publish
5. Run the just updated/created function and export it to IFC using Hypar user interface.
6. Open the IFC file in you preferred IFC viewer (I tested in Revit and 3DExperience).
7. You should not see any beam.

As a note, in 3DExperience, empty IFCProxy elements are created on the tree corresponding to the beams. See attached capture showing floors created with not issue and beams appearing as empty proxies.

**Expected behavior**
To be able to see beams exported in IFC.
In the capture, each floor should be surrounded by a beam on each edge.

**Screenshots**
![image](https://user-images.githubusercontent.com/2106720/72571324-63380900-3913-11ea-9576-4b500d00fa90.png)

**Desktop (please complete the following information):**
 - Wndows 10.

**Additional context**
- VS2017

**Comment by ikeough** [comment]
Thanks for this report @angellinares, and sorry for the delay in responding. It looks like you're using CATIA or Digital Project. If so can you confirm which version. I'm guessing that they're not showing up because they use a geometric representation only supported in IFC4 and , we've found, not entirely supported everywhere. Knowing what application you're using will help us to know what we should expect to be supported.

Also, if it's easy to test, you can try updating to 0.5.x and see if that helps.

**Comment by ikeough** [comment]
Possibly related to https://github.com/hypar-io/Elements/issues/189.

**Comment by angellinares** [comment]
Hi @ikeough , thanks for the reply. I didn't share it here but I also tried in Revit 2018 with similar results.

I'm using Catia 3DExperience 2019.

I hope that this helps. Let me know if you could need anything else from me.

Cheers.

**Comment by ikeough** [comment]
Possible related to #189.

**Comment by ikeough** [comment]
Beams import into ArchiCAD but have incorrect profile rotation:
![image](https://user-images.githubusercontent.com/1139788/79603416-2bbb3300-80a1-11ea-9e77-494328f4acb2.png)

**Comment by ikeough** [comment]
Solibri imports beams, and those going in one direction have the correct rotation while those going in another direction do not:
![image](https://user-images.githubusercontent.com/1139788/79603792-d5022900-80a1-11ea-9689-94a06b81f297.png)

**Comment by ikeough** [comment]
Identifiers for columns are created in Revit, but no geometry is created:
![image](https://user-images.githubusercontent.com/1139788/79604026-404bfb00-80a2-11ea-8b7b-dc1ebb484938.png)

**Comment by ikeough** [comment]
The applications listed here, and possibly those in #189 do not support two IFC4 Entity types which would best be used to draw sweeps along paths, `IfcSurfaceCurveSweptAreaSolid` and `IfcFixedReferenceSweptAreaSolid`. The solution it to use `IfcExtrudedAreaSolid` which will not support curved paths. Paths need to be subdivided. Here we use an arbitrary subdivision amount. In the image below you can see the Elements representation of a circular beam around a mass created by converting that circle to a polygon and extruding it, and the IFC versions of the same from Solibri and ArchiCAD.
![image](https://user-images.githubusercontent.com/1139788/79615190-09341480-80b7-11ea-9c2c-55262e2c5d07.png)

**Comment by ikeough** [comment]
Here's a further example showing some straight beams which exhibit the correct profile rotation as it rotates through 360 degrees with varying levels of inclination:
![image](https://user-images.githubusercontent.com/1139788/79615675-3208d980-80b8-11ea-9108-3ebef862dfa6.png)
