### ISSUE TITLE
Hypar walls are not in the same place as Revit.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#249]
**Describe the bug**
Walls extracted from Revit appear to be extracted using one face of the wall to generate the Hypar `Wall`. In the attached image, you can see how the extracted walls do not align with the slab subtractions suggesting that either the inner face or the outer face of the Revit wall was used to create our extrusion as opposed to getting the center plane and extruding in both directions.

**Expected behavior**
Hypar walls extracted from Revit should be in exactly the same location.

**Screenshots**
![image](https://user-images.githubusercontent.com/1139788/74387654-f565ec80-4dad-11ea-85e1-d723818066b1.png)

**Comment by wynged** [comment]
Should be solved by #251 

here is the new wall appearance
![image](https://user-images.githubusercontent.com/5872187/74483238-0f71fe80-4e84-11ea-8b3e-8624ea1f19ca.png)
