### ISSUE TITLE
Divide by Length of a line throws exception

### ISSUE THREAD

**Issue by julillosamaral** [hypar-io/Elements#289]
**Describe the bug**
When calling DivideByLength on a line it throws the exception The line could not be created. The start and end points of the line cannot be the same
**To Reproduce**
In a new function use this code

```         
var line = new Line(new Vector3(56.5818440261517, 30.3883306741724),
            new Vector3(-22.4911511648547, -25.7940636457841));

line.DivideByLength(1);
```

**Expected behavior**
The method returns the List of lines

**Desktop (please complete the following information):**
 - OS: Microsoft Windows

**Additional context**
No other context

**Comment by ikeough** [comment]
In 0.7.0 I cannot get the `DivideByLength` method to fail using exactly the same code as shown above. This was modified in https://github.com/hypar-io/Elements/commit/1ab847cc04a851a09ff7aa57aa53bbc04e014ee7#diff-0f4ce8bd6b2d7cb028f85ee6ed5eeed1 by @anthonyhauck 13 days ago. I'm closing for now, but if you can get the problem to reappear, please let us know.
