### ISSUE TITLE
Point in Line

### ISSUE THREAD

**Issue by julillosamaral** [hypar-io/Elements#300]
**Is your feature request related to a problem? Please describe.**
Having a function that checks if a point is contained in a Line is useful and shouldn't be implemented each time

**Describe the solution you'd like**
A snippet of code
```
private static bool pointInLine(Line l1, Vector3 point) {
    return Math.Abs((l1.Start.DistanceTo(point) + l1.End.DistanceTo(point) - l1.Length())) < EPSILON;
}
```
**Describe alternatives you've considered**
No other alternative I can think

**Additional context**

**Comment by andrewheumann** [comment]
Line.PointInLine(Vector3 point) is in 0.7.2.
