### ISSUE TITLE
Embed logger in the platform

### ISSUE THREAD

**Issue by julillosamaral** [hypar-io/Elements#305]
**Is your feature request related to a problem? Please describe.**
I want to have a better insight on what my funcion is doing internally. This could help me track errors when I'm developing as well as when a user is using my function.

In the current process the way I did this is by using `Console.Writeln` which I don't think it's optimal.

**Describe the solution you'd like**
Have available a static function to log text into a textfile, it allows me to logger.Error, logger.Info or logger.Debug or similar.

It should also be easy to configure, in hypar.json specify the path where I want the log file.

In the server I imagine there could be a UI for the user or developer to have the logs available and there could even be an hypar console command to retrieve this logs from the server to the developer computer `hypar get-logs`

This can be optional to include/configure but it's a nice to have.

**Describe alternatives you've considered**
I considered installing a logger into the application but didn't know what could be the result in the server when executing my function.

**Additional context**
This is something I find useful to have a better insight on the app.

**Comment by ikeough** [comment]
This request seems related to Hypar, not Elements specifically. There's nothing to stop you from using a logging library in code that you write for Hypar. You'd just want to make sure that it's only used during debug because you don't want to write files to Hypar compute instances.
