### ISSUE TITLE
Store multiple shapes for testing

### ISSUE THREAD

**Issue by julillosamaral** [hypar-io/Elements#306]
**Is your feature request related to a problem? Please describe.**
As I'm developing I test with different shapes, some of them gives me issues I fix. But I would like to have a way to test previous versions of the shapes I have used before just to test that everything continues working as expected.

This is some kind of historical of the shapes.

**Describe the solution you'd like**
I would like to be able in development to save the different shapes I have worked before in order to easily test the algorithm I'm working on. This way I can do some type of regression testing and find new bugs or old bugs that are re inserted in the code.

**Describe alternatives you've considered**
I considered doing this with a unit test and creating new unit test one for each shape.

**Comment by julillosamaral** [comment]
Another option I thought was to create multiple hypar.json files which can be a bit confusing.

**Comment by ikeough** [comment]
A unit test is the way to go. You can even create a parameterized unit test where each parameterized test feeds the unit test one shape. I don't think we need to implement anything in Elements to support this.
