### ISSUE TITLE
Line TrimTo not working in YZ Plane

### ISSUE THREAD

**Issue by JeremyJamesG** [hypar-io/Elements#307]
**Describe the bug**
When using the Line TrimTo method in vertical plane, function returns null. i.e. intersecting a vertical line with an elevated horizontal line.

**To Reproduce**
 ```
Line l1 = new Line(new Vector3(0, 0, 0), new Vector3(0, 0, 10));
Line l2 = new Line(new Vector3(0, 5, 2), new Vector3(0, -5, 2));

Line l3 = l1.TrimTo(l2);

Assert.NotNull(l3);  
```

**Expected behavior**
I would expect the line to be trimmed if they are coplanar.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/31432498/80346419-0c48b500-88ae-11ea-815f-57f895b6e81a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by andrewheumann** [comment]
Thanks for this @JeremyJamesG. Just submitted a fix.

**Comment by andrewheumann** [comment]
This will be out in the next release. Thanks again for reporting.
