### ISSUE TITLE
Polygon does not override "PointAtInternal" method of Polyline

### ISSUE THREAD

**Issue by jeroenvanl** [hypar-io/Elements#322]
**Describe the bug**
Because the Polygon class does not override the "PointAtInternal" method of the Polyline class, a point can never be placed on the last segment.

**To Reproduce**
`output.Model.AddElement(new Elements.ModelPoints(new List<Vector3>{perimeter.PointAt(0)}));
        output.Model.AddElement(new Elements.ModelPoints(new List<Vector3>{perimeter.PointAt(1)}));`

**Expected behavior**
You expect points to be placed over the total length of the polygon, including the last segment.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Hypar CLI 0.7.1
Hypar Function Builder 0.1.3

**Comment by ikeough** [comment]
Thanks @jeroenvanl. When we discussed this on Discord I thought it was the other way around. It was overriding but was somehow broken. This is a good find. Thanks!
