### ISSUE TITLE
Inputs should support defaults

### ISSUE THREAD

**Issue by andrewheumann** [hypar-io/Elements#332]
**Is your feature request related to a problem? Please describe.**
As per Brittney Holmes, on discord: 
![image](https://user-images.githubusercontent.com/31935763/84313837-1f010b80-ab35-11ea-8ef6-63153f1d18c5.png)

**Describe the solution you'd like**
If input parameters supported default values, then the grasshopper plugin could populate those defaults with the values supplied at runtime, and users would immediately see a complete representation of what they had in grasshopper. It would also allow us to supply more sensible values than the middle of the range for functions with large ranges (e.g. the Levels by Envelope function, which defaults to 11m levels today)

**Comment by ikeough** [comment]
I would propose to make default constructors that generate _something_. For example, calling `new Polygon()` would create an L shaped polygon (just an idea).
