### ISSUE TITLE
Line.Trim(Polygon) does not trim correctly with concave polygons.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#355]
**Describe the bug**
`Line.Trim(Polygon)` does not work for concave polygons.

**Screenshots**
Neither the `inner` or the `outer` settings work.
![image](https://user-images.githubusercontent.com/1139788/88987455-cf180880-d28a-11ea-8e35-14622ed9cb01.png)
![image](https://user-images.githubusercontent.com/1139788/88987538-169e9480-d28b-11ea-85ac-e61afc5a83b4.png)

**Comment by andrewheumann** [comment]
The algorithm seems to handle concave polygons just fine -- the issue may be something else. Can you provide a set of test polygon + lines that were failing?
![image](https://user-images.githubusercontent.com/31935763/89032219-2efdc600-d302-11ea-9c67-318a768ab692.png)

**Comment by andrewheumann** [comment]
It looks like your lines start from *on* the polygon edges - is that true? that may have something to do with it

**Comment by ikeough** [comment]
That is true.
