### ISSUE TITLE
Visual Center of Polygons & Profiles

### ISSUE THREAD

**Issue by wynged** [hypar-io/Elements#380]
**Is your feature request related to a problem? Please describe.**
I want to find a point that is near center  of a shape, but is required to actually be inside the polygon.  Centroid does not satisfy this.

**Describe the solution you'd like**
Something like this VisualCenter https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc 
This is a code base where it is implemented. https://github.com/mapbox/polylabel 

**Describe alternatives you've considered**
I'm going to use a workaround where I cast a line from the centroid and trim that line with the surrounding polygon.  The midpoint of this trimmed line is guarunteed to be inside the polygon.

**Additional context**

**Comment by ikeough** [comment]
Substantially solve in #529. We can reopen if we think we want an exact solution.
