### ISSUE TITLE
Serialization.IFC: 2x3?

### ISSUE THREAD

**Issue by kjetilbk** [hypar-io/Elements#397]
I might've misunderstood something – but it seems to me like the `IFCModelExtensions.FromIFC` assumes IFC4? Is there a way to read an IFC 2x3 file? When trying, I receive errors such as `IFC.STEPParameterMismatchException: IFC.IfcWallStandardCase’s constructor expects 8 parameters but 9 parameters are provided.` due to the differences between IFC 2x3 and 4's APIs.

How are you currently working with IFC2x3 files? :D

**Comment by ikeough** [comment]
We aren't :) At some point many months ago we moved to IFC4. Most of the major BIM applications now support it. We did not have a requirement to read a lot of legacy IFC files, and supporting multiple versions of IFC was more than our tiny team could handle.

**Comment by kjetilbk** [comment]
I see, thanks for the explanation! :D :rocket:


(bisected my way to the commit btw, if anyone else ever wonders when the change happened: https://github.com/hypar-io/Elements/commit/fa31c132c940e901b53a0a40a781fd695555f0e3)
