### ISSUE TITLE
Site coordinates are incorrect in IFC.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#407]
**Describe the bug**
Site positions should be latitude, longitude, elevation in exported IFC. We currently only encode the latitude and longitude.

**Comment by ikeough** [comment]
Reported by @Moult when exporting from Hypar and attempting to open the IFC file in BlenderBIM. Please test in BlenderBIM when submitting.

**Comment by Moult** [comment]
From memory this was something to do with a required length of 3 to encode degrees, minutes, seconds? My memory is fuzzy.

**Comment by ikeough** [comment]
Updating the `IFCSite` Latitude and Longitude attributes to have seconds fixes the problem:
![image](https://user-images.githubusercontent.com/1139788/97375373-e493d300-1877-11eb-92d5-bf6e2430958d.png)
