### ISSUE TITLE
Sweeps to glb appears broken.

### ISSUE THREAD

**Issue by wynged** [hypar-io/Elements#417]
**Describe the bug**
The Sweep solid type doesn't generate valid geometry.  first noticed when trying to generate the geometry for a flow network class that draws connections using straight sweeps.  You can also see it in solid tests that produce invalid glb files.

**To Reproduce**
1. Go to "SolidTests.cs"
2. Click on Run Test for `SweptSolidPolygon`
3. Try to load the generated glb into a viewer, it will fail to open.
here is a sample.
[SolidTest.zip](https://github.com/hypar-io/Elements/files/5447669/SolidTest.zip)

**Expected behavior**
Valid glb file is generated.

**Screenshots**
babylon sandbox says `e[t] is null`

**Desktop (please complete the following information):**
 - Windows

**Comment by ikeough** [comment]
This was fixed in #413.

**Comment by ikeough** [comment]
This is verified.
