### ISSUE TITLE
glTF Generation assigns incorrect materials if materials share names

### ISSUE THREAD

**Issue by andrewheumann** [hypar-io/Elements#460]
**Describe the bug**
Elements are being assigned the wrong materials, if new materials are assigned with the same name. 

**To Reproduce**
Create a function
```
var panel1 = new Panel(Polygon.Rectangle(1, 1), new Material("Name", Colors.Red));
var panel2 = new Panel(Polygon.Rectangle(1,1), new Material("Name", Colors.Blue), new Transform(2, 0, 0));
output.Model.AddElement(panel1);
output.Model.AddElement(panel2);
```
New materials with distinct Guids are created, and the resulting panels have the correct material IDs assigned, but the resulting gltf renders both panels in the same color. 

**Expected behavior**
The panels should be different colors

**Screenshots**
![image](https://user-images.githubusercontent.com/31935763/101003494-4a861100-352e-11eb-8280-cb8373193a74.png)

**Comment by ikeough** [comment]
I believe we key materials by their name in the glTF processor. We should key them by their Id.
