### ISSUE TITLE
Support non-coplanar polylines

### ISSUE THREAD

**Issue by mattc** [hypar-io/Elements#461]
**Is your feature request related to a problem? Please describe.**
Elements.Geometry.Polyline have a validator that requires them to be coplanar. This makes it impossible to use polylines to drive arbitrary extrusions, like those needed for expressing MEP systems.

**Describe the solution you'd like**
Remove the `vertices.AreCoplanar()` validation on the current Elements.Geometry.Polyline class and remove any methods that assume coplanar polylines. A separate 2D Polyline Element can be introduced later if needed, e.g. to enforce compatibility with AutoCAD 2d polylines.

**Describe alternatives you've considered**
Keeping the current class coplanar and add a new 3D polyline class.

**Additional context**
Envelope By Centerline not only assumes coplanar polylines, but it assumes that they are parallel to the ground plane. Since the ground plane restriction is only enforced by UI and not by deserialization, it seems reasonable to require that the coplanar restriction will be too.

I propose changing :
- Validators.cs:PolylineValidator: remove AreCoplanar check.
- In the Elements.Geometry.Polyline definition:
  - Update header comments
  - Remove CheckCoincidenceAndThrow. It's protected and not used anywhere.
  - Update FramesInternal to stop assuming coplanar polylines, trying not to cause too much twistyness on extrusions in cases of orthogonal bends.
  - Leave Normal, TransformAt but comment that they're only meaningful for coplanar polylines
  - Leave ToClipperPath and Offset, but comment that they assume coplanar polylines and a Z-up normal. This is already unenforced and it doesn't look like they'll break.

**Comment by ikeough** [comment]
Do we propose to move the coplanar validator to Polygon’s constructor? Doing that and moving Normal() down to Polygon would probably be a nice clarification, assuming we intend Polygons to still be forced planar.

TransformAt is still meaningful for a Polyline, but we may need to adjust the logic for non planarity.

I propose that we leave Offset() on Polyline and throw a meaningful exception for non planar Polylines, updating the docs to reflect this exception will be thrown.

**Comment by mattc** [comment]
Polygons already have their own validator for this.

Agree on TransformAt. We should use the same normal strategy that's we choose for Frames. Perhaps Normal should take a parameter.

Offset just throws away the Z coordinates, so it's not about being coplanar. A polyline drawn on the surface of a wall would be coplanar but would still behave unexpectedly in this function. If we add validation now, I'd enforce approximately equal Z coordinates instead.

**Comment by ikeough** [comment]
`Offset()` really makes the need for `Polygon2` obvious. 

What do you mean that `Normal()` should take a parameter?
