### ISSUE TITLE
Bezier.Length() is wrong

### ISSUE THREAD

**Issue by andrewheumann** [hypar-io/Elements#462]
**Describe the bug**
Bezier.Length() reports a value that is very off. 

**To Reproduce**
Compare Bezier.Length() to Bezier.ToPolyline(100).Length() — the difference is for me nearly a factor of 2.

**Comment by Gytaco** [comment]
I'm working on a bezier thing atm I assume no updates?

**Comment by iainsproat** [comment]
I've attempted a fix at this bug: https://github.com/hypar-io/Elements/pull/757

While my PR fixes and adds tests for the existing algorithm, the existing algorithm (linear interpolation) seems relatively inaccurate and this may need further work.  For example, the following results in a length of `9.8` and not the expected `10.0`, an (in)accuracy of >2%.

```
[Fact]
public void Bezier_Length_StraightLine()
{
    var a = Vector3.Origin;
    var b = new Vector3(5.0, 0.0);
    var c = new Vector3(10.0, 0.0);
    var ctrlPts = new List<Vector3>{a,b,c};
    var bezier = new Bezier(ctrlPts);

    var expectedLength = 10.0;
    Assert.Equal(expectedLength, bezier.Length(), 1);
    var divisions = 50;
    var polylineLength = bezier.ToPolyline(divisions).Length();
    Assert.Equal(polylineLength, bezier.Length());
}
```

**Comment by ikeough** [comment]
We can improve that slightly by increasing the number of samples, currently set at 50. But that's only going to get slower. There are other methods that we could try: https://stackoverflow.com/questions/29438398/cheap-way-of-calculating-cubic-bezier-length.
