### ISSUE TITLE
code gen for inherited types does not add the correct discriminator

### ISSUE THREAD

**Issue by wynged** [hypar-io/Elements#464]
**Describe the bug**
When one schema inherits from another, the parent schema needs a JsonInheritanceAttribute filled in with the discriminator of the child type.  Currently only the type name is filled in, not the entire class name which would include the namespace.

**To Reproduce**
1. Code gen the type `https://dev-api.hypar.io/schemas/FlowPort` which inherits from FlowNode
2. Create a flow node and add it to a model.
```
            var model = new Model();
            model.AddElement(new FlowPort(true, 10, Guid.NewGuid(), Vector3.Origin, Guid.NewGuid(), ""));
            var json = model.ToJson();
            var deserial = Model.FromJson(json);
            Assert.NotEmpty(deserial.Elements);
            Assert.Contains("Elements.FlowNetwork.FlowPort", json);
```
3. Serialize the model and then try to deserialize.

**Expected behavior**
The serialization and deserialization tests in the code above should succeed, you can see the JSON serialization issue by adding looking at the text in the JSON variable above.  The discriminator is wrong.
The hack to fix this is to go into the FlowNode.g.cs file that was generated and add the namespace before `FlowPort` in the `JsonInheritanceAttribute`.  Adding `Elements.FlowNetwork.` will make the tests above pass.

**Screenshots**
working class attributes.
![image](https://user-images.githubusercontent.com/5872187/101697543-00c58b00-3a46-11eb-8b99-56f8a711b39a.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by ikeough** [comment]
Is this issue moot now that we've removed the `JsonInheritanceAttribute` from code generation?
