### ISSUE TITLE
Instancing has unexpected transform behavior

### ISSUE THREAD

**Issue by wynged** [hypar-io/Elements#475]
**Describe the bug**
While creating instances  modification to an transform are applied to all of the instances that are created using that trasnform variable.  

**To Reproduce**
```C#
            output.Model.AddElement(new Line(new Vector3(), new Vector3(5, 0)));
            var t = new Transform();
            var inst1 = WyeFitting.CreateInstance(t, "");
            output.Model.AddElement(inst1);

            t.Move(new Vector3(1, 0, 0));
            // t = t.Moved(new Vector3(1, 0, 0));
            var inst2 = WyeFitting.CreateInstance(t, "");
            output.Model.AddElement(inst2);
```
This code will create the following image, where both fittings have been moved to the exact same, translated, location.
![image](https://user-images.githubusercontent.com/5872187/104042818-f1527280-51a8-11eb-9fc9-d0ea7d049e6b.png)

**Expected behavior**
I would expect the two instances to have different locations.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by ikeough** [comment]
The behavior as shown above is expected `Transform.Move` mutates the transform. `Transform.Moved` creates a new transform. As such, both instances referencing the transform have the same location.

**Comment by wynged** [comment]
Closing thought, I think this is a bit unusual becuase this will be true for these elements at this moment, but when this model is serialized and deserialized it will no longer be true.  These pieces of content don't reference the same transform in the Model, it's only true while the are in memory and have been created like this.

**Comment by ikeough** [comment]
The same is true for any reference to any type that is not an element. The work on representation doesn't "fix" this either because the transform is still on the element. 

Does the consumer of the JSON have a reasonable expectation that the deserialized model will exactly mirror the pre-serialized model?
