### ISSUE TITLE
Provide a surface with holes Representation

### ISSUE THREAD

**Issue by anthonyhauck** [hypar-io/Elements#493]
**Is your feature request related to a problem? Please describe.**
Space planners wish to represent 2D spatial zones that may have gaps created by other immovable space allocations, such as building service cores, horizontal circulation, or previously allocated space. Elements lacks a managed representation of a displayable surface with holes in it.

**Describe the solution you'd like**
An Element representation similar to Lamina that would accept a list of openings similar to Floor creation.

**Describe alternatives you've considered**
Overlapping Polygons, but much management of their relationship is necessary by the developer.

**Additional context**
This came as a customer request from the Jacobs Krakow development team on 2021.01.25.

**Comment by ikeough** [comment]
Solved in #592
