### ISSUE TITLE
docfx cicd blocked by master branch protections

### ISSUE THREAD

**Issue by cdriesler** [hypar-io/Elements#509]
On merge to `master`, the `build-docs` step runs fine until it has to commit the new docs:

![0205_error](https://user-images.githubusercontent.com/20760128/107055810-ac1d6280-679f-11eb-9fd0-04d905c55d91.PNG)

We should either find a way to allow a 'bot user' through, or come up with another solution.

The usual alpha build and release step is still working, even if the repo shows an angry red X for now.

**Comment by mattc** [comment]
What about doing this on push-to-branch or PR? I'll want to review and/or correct the docs sometimes before merging.

**Comment by cdriesler** [comment]
Fair call, will have a PR with this adjustment in shortly.

**Comment by cdriesler** [comment]
Resolved in #510
