### ISSUE TITLE
Provide commonly useful geometric properties, operations, and comparisons

### ISSUE THREAD

**Issue by anthonyhauck** [hypar-io/Elements#56]
Some of this I'll pull directly from the Shapely functionality set: https://toblerity.org/shapely/manual.html

**Polygon Properties**

- Area (For closed shapes. Polygon? BBox?)
- Bounding box for planar geometry (I realize the user can construct a BBox. If you want to leave this as is, I'm okay with it, but the libraries I've look at all seem to provide this information as a property of the geometric entity)
- Center - Returns the center of the BBox. Not strictly necessary, occasionally convenient.
- Centroid 
- Length (in Polygon land, this is equal to the linear circumference).

- PointWithin - Returns a cheaply computed point that is guaranteed to be within the geometric object. We could relegate this somewhere else as a method that can be performed on a Polygon.

**Geometric Comparisons**

To keep this simple, I thought these comparisons could happen as if all 2D geometries shared a plane. If you think these should respect z-axis separation, so that Polygons that would return "True" to an overlap test would instead return "False" if they differ in z-axis comparison, just let me know. I'm okay either way, we would just want our implementation to be consistent in this regard.

This is isn't really a design, just a summary of desired functionality. (I realize things like "IsContaining" could just be called "Contains" but I was imagining a consistent convention for comparisons. I'm okay either way.) 

Shapely thinks about Polygons as having 3 distinct concepts...

- Interior
- Boundary
- Exterior

...and several of these defintions assume that distinction.

- ConvexHull - Returns a Polygon representing the convex hull of a set of coplanar points (Vector3?)
- Difference(Geometry1, Geometry2) Returns a list of Polygons representing the geometric difference between Geometry1 and Geometry2.
- Distance(Geometry1, Geometry2) Returns the minimum distance between Geometry1 and Geometry2.
- Intersection(Geometry1, Geometry2) Retruns a list of Polygons representing the geometric intersections between Geometry1 and Geometry2.
- IsCountainedByGeometry1, Geometry2) - Returns True if Geometry1’s boundary and interior intersect only with the interior Geometry2 (not its boundary or exterior).
- IsContaining(Geometry1, Geometry2) - Returns True if Geometry2’s boundary and interior intersect only with the interior Geometry1 (not its boundary or exterior).
- IsCovering(Geometry1, Geometry2) - Returns True if the combination of Geometry1's boundary and interior are wholly coincident with the combination of Geometry2's boundary and interior.
- IsDisjoint(Geometry1, Geometry2) - Returns True if Geometry1 and Geometry2 do not touch or intersect.
- IsIntersecting(Geometry1, Geometry2) - Returns True if Geometry1 and Geometry2 boundaries or interiors intersect in any way.
- IsOverlapping(Geometry1, Geometry2) - Returns True if IsCovering is False and IsIntersecting is True.
- IsTouching(Geometry1, Geometry2) - Returns True if Geometry1 and Geometry2 have at least one point in common and their interiors do not intersect with any part of the other.
- Midpoint(Vector3, Vector3) (I realize you can get this with PointAt(0.5) so this would be a mere convenience).
- RemoveColinear(IEnummerable<Vector3>) Not sure if we need this. I implemented one to safely construct a Polygon with unique points. Not sure if you have that already through Clipper.
- Union (Geometry1, Geometry2) Returns a Polygon representing the geometric union of Geometry1 and Geometry2.

**Geometric Operations**
Except in the first case, I don't know if you want to construct a new one or create a transform for the existing Geometry.

- Copy(Geometry) - Returns a new identical Geometry.
- Mirror(Geometry, Line) - Reflects Geometry around the delivered line.
- MoveBy(Geometry, Vector) - Returns Geometry displaced from the original Geometry. 
- MoveTo(Geomtry, FromPoint, ToPoint) - Convenience. Constructs the vector for MoveBy for the user. Otherwise like MoveBy.
- Rotate(Geometry, Angle, Pivot) - Rotates the Geometry by the delivered radians around its (Center? Centroid? I used Centroid) by default or around a delivered (Vector3? Point Element?)
- Scale(Geometry, Vector) - Scales the Geometry by the delivered vector factors from its (Center? Centroid? I used Centroid) by default or from a delivered (Vector3? Point Element?)

**Elements**

- Add a Point element that implements an IVector interface?

**Comment by arif-hanif** [comment]
i would love to help implement some of these @hummingburd @ikeough have any of them been started

**Comment by hummingburd** [comment]
Hi Arif. The 2D stuff has largely been implemented. I don't know if anyone beyond Ian and I have touched these most recent three. Ian?

**Comment by ikeough** [comment]
The most recent three haven't been advanced yet. They're open for anyone to contribute.

**Comment by ikeough** [comment]
Closing this because most of the above is available for Polygons.
