### ISSUE TITLE
Solid silently fails to generate glb (Regression)

### ISSUE THREAD

**Issue by andrewheumann** [hypar-io/Elements#585]
**Describe the bug**
A `ConstructedSolid` that used to generate a GLB easily prior to #573 now fails silently.

**To Reproduce**
check out branch `glb-generation-fails` and run `SolidTests.ConstructedSolidProducesValidGlb`

**Expected behavior**
It should produce a glb that looks like this, as it used to: 
![image](https://user-images.githubusercontent.com/31935763/118577114-cd56fd00-b757-11eb-94bf-321d60fedb72.png)

**Additional context**
I tracked this as far as the `Csg.Solid ToCsg(this Solid solid)` method, but I was unable to isolate a specific problem. In the previous version, the sold was triangulated, resulting in a csg with 74 polygons. This solid proceeds through `ProcessSolidsAsCSG` with no problem. The new version, post vertex merging, creates a solid with 10 polygons, but when it goes through `ProcessSolidsAsCsg` it outputs an invalid CSG with 0 faces from `csg.Union(solids);` That's all I know!

**Comment by ikeough** [comment]
This seems to be a clockwise wound polygon face created from the solid.
![image](https://user-images.githubusercontent.com/1139788/118904232-51cb8c00-b8ce-11eb-9b25-a1c549d540df.png)
And the original data in the JSON is CW as well.
![image](https://user-images.githubusercontent.com/1139788/118904409-b0910580-b8ce-11eb-8581-fb55163af218.png)
I believe these CW wound polygons would cause a CSG that is inside out, and this is perceived by the CSG algorithm to be a void, so the Solid voids itself during the Union call.

**Comment by ikeough** [comment]
The cause of this is that Solids with planar faces (all of our solids) are no longer having those faces tessellated when converted to CSG unless the face has a hole. My guess would be that the tessellator took the CW wound data and produced enough facets that the CSG operation new what to do, or that the facets were generated with the correct orientation. The data has a lot of colinear points. It's also possible that we can't send a polygon with colinear vertices directly through to CSG.

**Comment by andrewheumann** [comment]
The polygon in the JSON is not incorrectly wound. It is CCW with respect to the -Z — you're looking at the bottom face of the Brep. I double-checked the input data: all polygons are wound correctly, CCW with respect to outward-facing normals

![winding](https://user-images.githubusercontent.com/31935763/119487684-b2702400-bd27-11eb-89b0-6c55e87186c2.gif)
.

**Comment by wynged** [comment]
I believe I have a minimum test case of this, or a related issue.  
The failure seems to be related to some vertices being "shadowed"? by others during some sort of analysis internal to the Csg library.  A minimum test case where you can see this is here. 
```
        [Fact]
        public void Lamina()
        {
            var r = new Polygon(new List<Vector3> {
              new Vector3(  0.0, 3.0, 0.0) , // succeeds if y -> 3=>4 and below
              new Vector3(  0.0, 0.0,  0.0) ,
              new Vector3(  5.0, 0.0,  0.0) ,
              new Vector3(  5.0, 4.0,  0.0) ,
              new Vector3(  4.0, 4.0,  0.0) ,
              new Vector3(  4.0, 5.0,  0.0) ,
              new Vector3(  2.0, 5.0,  0.0) ,
              new Vector3(  2.0, 3.0,  0.0) }); // succeeds if y -> 3=>4 and above
            var lamina = new Lamina(r, false);

            var csg = new Csg.Solid();
            var ucsg = csg.Union(lamina._csg);

            Assert.Equal(lamina._csg.Polygons.Count, ucsg.Polygons.Count);
        }
```
As indicated in the comments, if you change the "depth" of the last notch to 4, the solid that exists after unioning will be identical to the one before.  If however you leave the values at 3, then the right vertex is "shadowed" and I believe this contributes to the union failing.
The image below shows a polygon that fails to produce correct csg geometry when it is processed.  
![image](https://user-images.githubusercontent.com/5872187/119763314-499ac000-be7d-11eb-9a54-a3be27cfef83.png)

**Comment by andrewheumann** [comment]
I'm not sure if what @wynged is pointing to is the same issue or not, but I am having more trouble with GLB generation. I have a lot of elements that turn into funny triangles, and this is affecting a customer workflow. As it stands I have to downgrade everything to 0.8.5 to keep this from happening. Very flat elements, like laminas and shallow extrusions of complex polygons are getting turned into weird triangulated messes that nearly disappear. 

With 0.8.5:
![image](https://user-images.githubusercontent.com/31935763/119903173-4dc6ec00-bf16-11eb-9ae6-680c7e1a3fe6.png)
With 0.9.0:
![image](https://user-images.githubusercontent.com/31935763/119903468-bd3cdb80-bf16-11eb-8263-286574e43c00.png)

Here is an example model for which this is happening:
[c2e04beb-ea87-45fe-aa57-4bf21286c358_9dfa2429-26cc-4f64-8dff-cb56cfa17ad5_elements.zip](https://github.com/hypar-io/Elements/files/6557076/c2e04beb-ea87-45fe-aa57-4bf21286c358_9dfa2429-26cc-4f64-8dff-cb56cfa17ad5_elements.zip)

**Comment by ikeough** [comment]
@andrewheumann Can we close this, or is this still more work to be done?

**Comment by andrewheumann** [comment]
This is believed fixed.
