### ISSUE TITLE
Get Bounding Box from Element

### ISSUE THREAD

**Issue by andrewheumann** [hypar-io/Elements#598]
Our BBox3 methods are not easy to use if you're starting with an element — you need to figure out what kind of element it is, maybe get into its representation, then its solidOperations, then its solids, then its vertices, etc. We should add utility methods to make it easy to get a bounding box from any element that has geometry. 

cc: @M-JULIANI

**Comment by ikeough** [comment]
Geometric elements now call `UpdateBoundsAndComputeSolid` internally, which _should_ compute the correct bounding box which is then available via the `Bounds` property.
