### ISSUE TITLE
Schema Changes break existing code

### ISSUE THREAD

**Issue by andrewheumann** [hypar-io/Elements#676]
We want to support the evolution of schemas over time. However, if schemas change, the constructor for that class changes too. Even if we were to codegen default arguments for all properties (we don't, we only do for those we inherit from Element or GeometricElement), adding a new property means adding a new argument to the constructor.

We should consider defaulting to generating empty constructors, and preferring `new Foo {Property = blah, Property2 = blah}` syntax. Perhaps there are other ways to ensure backwards compatibility for constructors — `hypar init` could preserve existing, previously generated constructors, and only add new overloads if all required properties are present in the existing constructor.

**Comment by ikeough** [comment]
Is this an Elements issue or a Hypar issue?

**Comment by andrewheumann** [comment]
just needed to put it somewhere! Seems relevant to Elements.CodeGeneration, and it's something non-Hypar users of elements will run into too.

**Comment by ikeough** [comment]
This is now implemented correct @andrewheumann ? I've seen empty constructors show up in code gen.

**Comment by andrewheumann** [comment]
Yes, empty constructors are now implemented!
