### ISSUE TITLE
Parametric Profile

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#696]
Many things in the built world are defined by a profile swept along a path. Concrete bridge sections, structural steel, etc. Elements currently has a `Profile` type that is useful for representing a "perimeter" with one or more "void" curves. There are classes like `WideFlangeProfileServer` which add onto this the idea of a catalog of profiles. 

Adding a new profile type to Elements requires either writing and submitting code into Elements or writing code for your own profile type in your project. Profiles are generally defined as a set of vertices in the XY plane, each vertex offset by x and y from a center line. In the case of structural profiles though, to use one example, the shape of the profile is defined by a set of parameters that are usually listed in the supplier's catalog like: "d" for depth, and "t" for thickness. The code to generate the profile then takes the form of offsetting relative to the previous point, as you move around the profile in the CCW direction by amounts defined by those parameters. 

A general purpose method for describing a parametric profile in terms of parameters to be supplied by a catalogue, would enable users to define new Elements profile types without writing code.

This proposal is for the creation of a `ParametricProfile` type which takes as its parameter a configuration consisting of the following:
- A series of named parameters, which represent numerical values.
- A series of vertex location expressions which represent the location of each vertex in terms of the named parameters as two mathematical expressions, one for x and one for y.
The `ParametricProfile` constructor "compiles" the expressions, emits errors as necessary where properties are unknown or the expressions are incorrectly defined, and constructs a profile. Profile factories, like `WideFlangeProfileFactory` could then implement expression-based constructions of profiles based on databases of parameter values. 

Requirements:
- Expressions must be parsable by C# (the language of Elements).
- Expressions must be serializable/deserializable to/from JSON.

What this does not need to be:
- A constraint-based sketching environment with point constraints defined by the parameters. Parameters are known. Users should be able to create profiles that have incorrect shapes.

**Comment by cdiggins** [comment]
Hi @ikeough could a profile just be an arbitrary closed 2D shape represented as an array of cubic bezier curves? Instead of arbitrary expressions? Each curve would have 4 control points. I think one could get a pretty good accuracy, but for machining/construction, it might not be accurate enough.

**Comment by ikeough** [comment]
@cdiggins Just seeing this now, apologies for the delayed response. Yes, that could work, but `Profile` as it is now only supports one exterior polygon and a number of interior void polygons. We have another type, `Contour`, which is an array of curve types (`Line`, `Bezier`, `Arc`), which has not received much development and could be the target for what you're suggesting.

**Comment by ikeough** [comment]
This was implemented in #697.
