### ISSUE TITLE
Add LastUpdated property to Element.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#73]

**Comment by radumg** [comment]
👍 for this.

Just in case this it's useful whilst you look at this property to consider others too, here's what our `Metadata` OpenAPI spec looks like at the moment. All the object models that we use in the current project have this as an `allOf` reference.

```yml
Metadata:
      type: object
      properties:
        Id:
          type: string
          format: uuid
          minLength: 30
          maxLength: 36
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        Name:
          type: string
          minLength: 3
          example: "Object name"
        DateCreated:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        CreatedBy:
          $ref: '#/components/schemas/User'
        DateLastModified:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        LastModifiedBy:
          $ref: '#/components/schemas/User'
```

**Comment by ikeough** [comment]
I'm closing this. I'm not going to do it. On thinking about this further, this is something that should live at the level of your DB/API. It has nothing to do with the representation of the data that is a column, beam, etc. What I would recommend regarding the above is that you have a property in that schema called 'Model' which can be `oneOf` any of the available model types. IOW, use composition.
