### ISSUE TITLE
Normals are incorrect for content

### ISSUE THREAD

**Issue by ikeough** [hypar-io/Elements#759]
The normals of exported content appear to be merged, causing incorrect lighting.

**Screenshots**
![image](https://user-images.githubusercontent.com/1139788/149554735-dd584752-9499-4c60-b6fa-af2dd4a7f481.png)

**Comment by andrewheumann** [comment]
I think this is not an elements bug. I think this is a bug in the revit exporter's gltf creation code: https://github.com/hypar-io/Revit/blob/308a197cc096a093ad342b1a7ad5b52a79968cd5/Hypar.Revit/src/Content/ElementMeshUtils.cs#L106

**Comment by andrewheumann** [comment]
(and it may already be fixed there. I think content exported recently looks totally fine)

**Comment by ikeough** [comment]
This is a Revit converter bug, and I have received assurances that there is no version of the converter currently available that has vertex merging (the source of the distorted normals) enabled.
