### ISSUE TITLE
`Line.TrimTo()` error thrown when already at the trimming edge

### ISSUE THREAD

**Issue by gon** [hypar-io/Elements#841]
**Description and repro steps**
Given I have 3 or more non-parallel lines
And I extend them all to ensure they all intersect each other (although only some don't already)
And I trim them all so that I only keep the edges "interior" to the resulting closed shape/polyline
Then the trim operation would throw an error for those which needed to be extended because they are already exactly at the trimming edge

**Expected behavior**
I would prefer if it would not throw an error, so that I don't need to keep track or check which Line pairs meet this criteria, in my case, because they were just extended.

**Desktop (please complete the following information):**
 - OS: macOS 12.4, Chrome 103.0.5060.114

**Comment by gon** [comment]
```
// Max depth
var maxDepth = frontSetback
    .Offset(input.MaximumDepth, true)
    .ExtendTo(sideSetbacks);
model.AddElement(maxDepth);

// Permitted footprint
foreach (var sideSetback in sideSetbacks)
{
    try
    {
        frontSetback = frontSetback.Reversed().TrimTo(sideSetback);
        maxDepth = maxDepth.Reversed().TrimTo(sideSetback);
    }
    catch (Exception exception)
    {
        // Suppressed error for unnecessary trims
    }
}
```

**Comment by andrewheumann** [comment]
Having trouble reproducing this one. I copied your code and removed the try/catch, and made up some values for `frontSetback` and `sideSetbacks`:
```csharp
var frontSetback = new Line((0, 0), (10, 0));
var sideSetbacks = new List<Line> {
    new Line((-1, -1), (-1, 5)),
    new Line((11, -1),( 11, 5))
};
// Max depth
var maxDepth = frontSetback
    .Offset(1, true)
    .ExtendTo(sideSetbacks);

// Max footprint
foreach (var sideSetback in sideSetbacks)
{
    frontSetback = frontSetback.Reversed().TrimTo(sideSetback);
    maxDepth = maxDepth.Reversed().TrimTo(sideSetback);
}
```

And it ran without exception. So it might be triggered by something specific to the geometry you're actually working with. 

Can you do me a favor and try replacing your code snippet above with this one, which will try to dump out the geometry that's causing the issue:
```csharp
// Max depth
var maxDepth = frontSetback
    .Offset(input.MaximumDepth, true)
    .ExtendTo(sideSetbacks);

// Max footprint
foreach (var sideSetback in sideSetbacks)
{
    var dataDump = new Dictionary<string, object>();
    try
    {
        dataDump["frontSetback"] = frontSetback;
        dataDump["sideSetback"] = sideSetback;
        dataDump["maxDepth"] = maxDepth;
        frontSetback = frontSetback.Reversed().TrimTo(sideSetback);
        maxDepth = maxDepth.Reversed().TrimTo(sideSetback);
    }
    catch
    {
        var errorData = dataDump.ToString();
        // dump out the error data somewhere — uncomment line below as appropriate.
        // if you're running the function on hypar:
        // output.Warnings.Add(errorData);

        // if you're running the function locally (e.g. with `hypar run` or `hypar test generate`)
        // System.IO.File.WriteAllText("debugging_output.json", errorData);
    }
}
```
Uncomment the appropriate line and paste the resulting text here, and we can take a look at what's causing this error.

**Comment by ikeough** [comment]
Closing this until we can get a reproduction case. @gon?

**Comment by gon** [comment]
Sounds good to me!
