### ISSUE TITLE
Polyline.Frames inconsistent results

### ISSUE THREAD

**Issue by sanchez** [hypar-io/Elements#855]
I was playing around with the Polyline.Frames function and noticed that the "normal" of the transform so to speak is not always point in the same direction. Here are some screenshots of what I have produced so far:

![image](https://user-images.githubusercontent.com/5264697/183580088-ee47b479-55e1-4bd4-8905-780b0ebe02d8.png)

![image](https://user-images.githubusercontent.com/5264697/183580199-ab6d3932-f95e-43a3-a024-57c6295e45c0.png)

The idea is that the blue line represents the "normal" of the transform, which is just achieved by transforming a (0, 0, 1) vector.

Some additionally testing has shown that I seem to always get the "backwards" normals when the angle is accute:

![image](https://user-images.githubusercontent.com/5264697/183582142-62d90f5d-5300-4fd3-b4c9-5edc9aa6f183.png)

**To Reproduce**
```csharp
Polyline curve;
List<Element> items = new List<Element>();

Vector3 originPoint = new Vector3(0, 0, 0);
Vector3 pointingPoint = new Vector3(0, 0, 1);
Vector3 upPoint = new Vector3(1, 0, 0);
Vector3 sidePoint = new Vector3(0, 1, 0);

List<(Vector3 location, Vector3 direction, double magnitude, Color? color)> vectors = new List<(Vector3 location, Vector3 direction, double magnitude, Color? color)>();
Transform[] transforms = curve.Frames(0, 0);
foreach (Transform transform in transforms)
{
    Vector3 transformedOrigin = transform.OfPoint(originPoint);
    Vector3 transformedPointing = transform.OfPoint(pointingPoint);
    Vector3 transformedUp = transform.OfPoint(upPoint);
    Vector3 transformedSide = transform.OfPoint(sidePoint);

    vectors.Add((transformedOrigin, (transformedPointing - transformedOrigin), 2, Colors.Blue));
    vectors.Add((transformedOrigin, (transformedUp - transformedOrigin), 2, Colors.Red));
    vectors.Add((transformedOrigin, (transformedSide - transformedOrigin), 2, Colors.Green));
}

ModelArrows arrows = new ModelArrows(vectors);
items.Add(arrows);

return items;
```

**Expected behavior**
The blue lines/"normals" would all point along the curve in a similar direction?

**Desktop (please complete the following information):**
 - OS: Firefox, Windows 10

**Comment by andrewheumann** [comment]
Thanks for reporting this, we'll look into it!

**Comment by andrewheumann** [comment]
Also, just so you know, you can do `Transform.ToModelCurves()` to get r,g,b colored visualization of transform axes :)

**Comment by andrewheumann** [comment]
This is fixed now, should go out with the next release (or the next alpha if you need it ASAP!)

**Comment by sanchez** [comment]
Awesome, thanks so much
