### ISSUE TITLE
Unable to inherit from Curve

### ISSUE THREAD

**Issue by sanchez** [hypar-io/Elements#865]
**Describe the bug**
On Curve the Curve.RenderVertices is marked as `internal abstract` meaning that other assemblies cannot create their own Curve definitions.

**Expected behavior**
Be able to inherit from Curve and provide custom Curve implementations.

Cheers,
Sanchez

**Comment by ikeough** [comment]
This will be fixed in 2.0 through #957 where we create the `IBoundedCurve` interface and the `BoundedCurve` base class, where you can supply an implementation of `GetSubidivisionParameters(...)`.
