### ISSUE TITLE
feature request: 2D Line / Network thickening

### ISSUE THREAD

**Issue by andrewheumann** [hypar-io/Elements#893]
### Problem Summary
I need a method to create a clean, thickened `Profile` or `Profile[]` boundary from a "centerline network".

If I have an array of `Line`s (maybe `Polyline`s) — which are possibly disconnected from each other, and possibly connected with more than 2 at a given vertex, I want to be able to "thicken" this network. This is similar to a "wall join" scenario, or common "stroke" algorithms in drawing applications. This is an example of desired behavior (red is input, black is output):
<img width="669" alt="image" src="https://user-images.githubusercontent.com/31935763/192526960-cf0020b7-d9b8-4533-96e4-b00901d39287.png">

This example was produced with the following code:
```csharp
var offsets = lines.SelectMany(l => l.ToPolyline(1).Offset(offsetDistance / 2, EndType.Square)).Select(p => new Profile(p));
var union = Profile.UnionAll(offsets);
```

This works OK, but it does a poor job with non-right-angle corners:
<img width="814" alt="image" src="https://user-images.githubusercontent.com/31935763/192527603-9ab57177-050b-417f-97a0-843148cf758b.png">

Ideally, I could do something like:
```csharp
Line[] lines = ...;
double thickness = 10;
Profile[] thickenedLines = lines.Thicken(thickness); // (perhaps `lines.Offset`, but to me this suggests a one-sided offset)
```
and get a sensible result.

### Existing capabilities

It is conceivable that there is capability for this already in `Clipper`'s Offset capabilities, and we just need to add a method exposing the capability. 
If that doesn't work, we may also want to rely on the `Network` class to help sort the disordered bag of lines into a network topology if we need to compute this ourselves. 
We may also want to look at extending or leveraging `OffsetOnSide`, which already does some geometric polyline offset math. 

### Other notes:
 Eventually, it would be nice to also be able to specify parameters per-line. A contrived example, but something like:
 
 ```
 Polyline.Thicken(IEnumerable<(Polyline p, double leftThickness, double rightThickness)> polylines) {...}
 ```
(There's probably a better approach than an `IEnumerable` of tuples here, but setting separate thicknesses per line and per side would be nice).

**Comment by ikeough** [comment]
This is a great use case for the `Network` class.

**Comment by andrewheumann** [comment]
This was added in #902.
