### ISSUE TITLE
Loading model from serialized JSON results in too many materials which creates failures

### ISSUE THREAD

**Issue by wynged** [hypar-io/Elements#94]
Serializing and deserializing model from JSON text seems to have issues.  I've created this test in using they hypar generator, but I believe the error lies in the Model.cs class and how it loads from JSON, so I've put the issue here.  A mystery new 'black' material gets created on load, which causes errors when the materials are turned into a dictionary later. To do my tests I've had to remove this extra material from the materials after a model is loaded.

To recreate:
1) Create brand new hypar generator using `hypar new`
     1a) do `hypar init src` and return a valid output from your test functions execute method.  
     1b) I simply used `return new  Output(input.Model, 1.0); `
2) add the following line to the Test() function
`            System.IO.File.WriteAllText("../../../model.json", output["elements"].ToString()); `
3) run the test so that model.json gets written (should be in the same folder as FunctionTests.cs
3) In the FunctionTest contructor add the following lines (console write just to succinctly write the 3 material GUIDs and names.)
```
            var modeljson = System.IO.File.ReadAllText("../../../model.json");
            var mdl = Model.FromJson(modeljson);
            Console.WriteLine(string.Join("\n", mdl.Materials.Select(m=>$"{m.Key}: {m.Value.Name}")));
            _data.Model = mdl; 
```
4) if you debug and observe the `mdl` variable, you should see that it has 3 materials.  there are two materials with familiar GUIDs from the model.json, but there is an additional material, new GUID, also called 'black'

This will cause the execution to fail at a later step, but it is this moment where there are 3 materials in a model loaded from a json with only 2 materials that I believe the error is introduced.

**Comment by ikeough** [comment]
Thanks for the report @wynged. I'll take a look today.
