### ISSUE TITLE
[ReadMe] Examples Link Broken

### ISSUE THREAD

**Issue by johnpierson** [hypar-io/elements#95]
The example link in the readme is referring to the old link [here](https://github.com/hypar-io/elements/tree/master/csharp/test/Hypar.SDK.Tests). The new link appears to be [https://github.com/hypar-io/elements/tree/master/csharp/test](https://github.com/hypar-io/elements/tree/master/csharp/test) Just wanted to give you guys a heads up. 😉

**Comment by ikeough** [comment]
Thanks @johnpierson! This is fixed now.
