### ISSUE TITLE
When can we see hyparelements-py?

### ISSUE THREAD

**Issue by keshavanarayan** [hypar-io/Elements#964]
Is a Python version of Elements under works? If it is, then I am super excited for it :)

**Comment by ikeough** [comment]
No. There are a number of ways that you can use elements from Python though. See the IronPython project and Python.NET

**Comment by keshavanarayan** [comment]
Hi @ikeough, 

Thank you for getting back. Where is the `Elements.dll` file available?

**Comment by ikeough** [comment]
No worries at all! The Elements.DLL will be in the /bin/Debug folder. When built for release it'll be in /bin/Release.
