### ISSUE TITLE
Changing Line endpoints in-place

### ISSUE THREAD

**Issue by pederlh** [hypar-io/Elements#987]
Earlier, the properties `Start` and `End` for `Line` objects were public, so that the line endpoints could be manipulated in place. Since `Line` from version 2.0.0 inherits from `BoundedCurve`, this is no longer possible (see below).

https://github.com/hypar-io/Elements/blob/705f85f689c389a751bb5c54ad9c2010c3f3f346/Elements/src/Geometry/BoundedCurve.cs#L15

Being able to change simple lines in place was very useful, so I wonder if
* it is possible to change the two access modifiers in `BoundedCurve` to public or
* if there is another way of manipulating lins in-place.

**Comment by ikeough** [comment]
Would love to know the use case. Thinking here was that `Start` and `End` would report the start and end for all curve types, some of which are defined by start/end angles (arcs and ellipses), and some of which are defined by vertices or control points (indexedpolycurves, ellipses). A curve is a small type. Would it be possible to simply create a new one when you need to modify it?

**Comment by pederlh** [comment]
I did end up rewriting the code to create new curves instead of changing the existing ones. I think your thoughts on the curve type makes sense.
